---
name: CICD

on:
  push:
    branches: 
      - myworkflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push to DockerHub
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8 --push --tag aman7681/backendimage:latest ./server
    

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps: 
      - name: Pull image from docker hub
        run: docker pull aman7681/backendimage:latest
      - name: Delete old container
        run: docker rm -f crowdcontract-container
      - name: Run docker container
        run: docker run -d 0p 5001:5001 --name crowdcontract-container aman7681/backendimage

