name: run-test-cases
run-name: run-test-cases
on:
  push:
#    paths:
#      - 'server/**'
    branches:
      # - test
      # - main
      - dev
jobs:
  test-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install and test-db
        run: |
          cd server
          echo '${{secrets.DB_PASSWORD}}'
          npm i
          echo "MONGO_URI='mongodb+srv://aman:${{secrets.DB_PASSWORD}}@crowdcontract.ji7u87b.mongodb.net'
                PORT=5051
                JWT_SECRET_KEY='${{secrets.JWT_SECRET_KEY}}'
                AES_SECRET_KEY='${{secrets.AES_SECRET_KEY}}'
                SALT_ROUNDS=5" > .env
          npm run test-db
          echo "MONGO_URI='mongodb+srv://aman:${{secrets.DB_PASSWORD}}@crowdcontract.ji7u87b.mongodb.net/crowdContract'
                PORT=5051
                JWT_SECRET_KEY='${{secrets.JWT_SECRET_KEY}}'
                AES_SECRET_KEY='${{secrets.AES_SECRET_KEY}}'
                SALT_ROUNDS=5" > .env

          npm run test-api
          rm .env
      - name: Archive logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: db-test-logs
          path: |
             ${GITHUB_WORKSPACE}/server/logs/service.log
